FROM golang:1.18 AS build

WORKDIR /app

COPY . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o fullcycle main.go


FROM scratch

WORKDIR /app

COPY --from=build /app/fullcycle ./

EXPOSE 8000

CMD [ "./fullcycle" ]